version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: toro-testes-postgres
    environment:
      POSTGRES_DB: toro_testes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d toro_testes"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: toro-testes-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: src/Toro-Testes.Api/Dockerfile
    container_name: toro-testes-api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreSql: Host=postgres;Port=5432;Database=toro_testes;Username=postgres;Password=postgres
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__UserName: guest
      RabbitMq__Password: guest
      Jwt__SecretKey: super-secret-key-for-local-development-only-123456
    ports:
      - "8080:8080"

  worker:
    build:
      context: .
      dockerfile: src/Toro-Testes.Worker/Dockerfile
    container_name: toro-testes-worker
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DOTNET_ENVIRONMENT: Development
      ConnectionStrings__PostgreSql: Host=postgres;Port=5432;Database=toro_testes;Username=postgres;Password=postgres
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__UserName: guest
      RabbitMq__Password: guest
      Jwt__SecretKey: super-secret-key-for-local-development-only-123456
